#!/bin/bash

# Terminate instances already running
killall -q polybar

# Wait until processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

#launch polybar
polybar alex -r